version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true

services:
  apache:
    image: httpd:2.4.53
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/:delegated
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
  phpfpm:
    image: koromerzhin/phpfpm:8.1.11
    command: sh -c "composer install && php-fpm"
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    environment:
      APP_ENV: dev
      APP_SECRET: "6fc13c15dc2208ac54cfd2f3b348dbc7"
      COMPOSER_MEMORY_LIMIT: -1
      MAILER_DSN: "smtp://mailhog:1025"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      LOCK_DNS: semaphore
      DATABASE_URL: "mysqli://labstag:password@mariadb:3306/labstag_bdd"
    volumes:
      - ${PWD}/apps:/var/www/:delegated
      - ${PWD}/conf/php.ini-development:/usr/local/etc/php/php.ini
      - ${PWD}/conf/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"