version: "3.4"

networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true

services:
  phpfpmexec:
    image: koromerzhin/phpfpm:8.0.9-symfony
    command: sh -c "composer install"
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment:
      APP_ENV: dev
      APP_SECRET: "6fc13c15dc2208ac54cfd2f3b348dbc7"
      MAILER_DSN: "smtp://mailhog:1025"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      LOCK_DNS: semaphore
      DATABASE_BDD: labstag_bdd
      DATABASE_USER: labstag
      DATABASE_PASSWORD: password
      DATABASE_URL: "mysqli://labstag:password@mariadb:3306/labstag_bdd"
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    networks:
      - serverlampy
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  apache:
    image: httpd:2.4.51
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.labstag.rule=HostRegexp(`labstag.traefik.me`, `labstag.{ip:.*}.traefik.me`)"
        - "traefik.http.services.labstag.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:8.0.9-symfony
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    environment:
      APP_ENV: dev
      APP_SECRET: "6fc13c15dc2208ac54cfd2f3b348dbc7"
      COMPOSER_MEMORY_LIMIT: -1
      MAILER_DSN: "smtp://mailhog:1025"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      LOCK_DNS: semaphore
      DATABASE_URL: "mysqli://labstag:password@mariadb:3306/labstag_bdd"
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - serverlampy
      - net
    deploy:
      labels:
        - "traefik.enable=false"
