# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  twig:
    mode: "lazy"
  driver: "gd"
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public"
  filter_sets:
    cache: ~
    my_thumb:
      quality: 75
      filters:
        thumbnail: { size: [1320, 290] }
