# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Labstag\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Labstag\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  app.admin_menu_builder:
    class: Labstag\Menu\AdminMenuBuilder
    arguments: ["@knp_menu.factory"]

  app.admin_profil_menu_builder:
    class: Labstag\Menu\AdminProfilMenuBuilder
    arguments: ["@knp_menu.factory"]

  app.adminmain_menu:
    class: Knp\Menu\MenuItem # the service definition requires setting the class
    factory: ["@app.admin_menu_builder", createMainMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: admin_menu }

  app.adminprofil_menu:
    class: Knp\Menu\MenuItem # the service definition requires setting the class
    factory: ["@app.admin_profil_menu_builder", createMainMenu]
    arguments: ["@request_stack"]
    tags:
      - { name: knp_menu.menu, alias: admin_profilmenu }
  Labstag\Swagger\CheckPhoneSwaggerDecorator:
    decorates: "api_platform.swagger.normalizer.api_gateway"
    autoconfigure: false
  Labstag\Swagger\SearchUserSwaggerDecorator:
    decorates: "api_platform.swagger.normalizer.api_gateway"
    autoconfigure: false
