framework:
  workflows:
    attachment:
      type: "state_machine" # or 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: "method"
        property: "state"
      supports:
        - Labstag\Entity\Attachment
      initial_marking: start
      places:
        - start
        - averifier
        - valide
        - nonconforme
      transitions:
        submit:
          from: start
          to: averifier
        valider:
          from: averifier
          to: valide
        reenvoyer:
          from: [nonconforme, averifier]
          to: averifier
        annuler:
          from: averifier
          to: nonconforme
