framework:
  workflows:
    memo:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - Labstag\Entity\Memo
      initial_marking: start
      places:
        - start
        - brouillon
        - relecture
        - publie
        - rejete
      transitions:
        submit:
            from: start
            to: brouillon
        relire:
            from: brouillon
            to: relecture
        corriger:
            from: relecture
            to: brouillon
        publier:
            from: relecture
            to: publie
        rejeter:
            from: relecture
            to: rejete