name: Continuous Integration
on: [push]
jobs:
  install:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["7.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug
      - name: Install npm dependencies
        run: npm install
      - name: Validate composer.json
        run: |
          cd apps
          make composer-validate
      - name: Install Composer dependencies
        run: |
          cd apps
          make composer-dev
      - name: linter readme.md
        run: make linter-readme
      - name: Run PHP Code Sniffer
        run: |
          cd apps
          make linter-phpcs-onlyerror
      - name: Run PHP MD
        run: |
          cd apps
          make linter-phpmd
      - name: Run PHPMND
        run: |
          cd apps
          make linter-phpmnd
      - name: Test lancement bootstrap
        run: make encore-dev
      - name: Run twigcs
        run: |
          cd apps
          make linter-twigcs
      - name: Run Acceptance Tests
        run: |
          cd apps
          make tests-behat
      - name: Run Tests
        run: |
          cd apps
          make tests-simple-phpunit-unit-integration
  docker:
    needs: install
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: 'Docker swarm init'
          run: docker swarm init --default-addr-pool 10.20.0.0/16
        - name: 'Create proxy network'
          run: make docker-create-network
        - name: 'Build containers'
          run: make docker-deploy
        - name: 'Make sleep'
          run: make sleep
        - name: 'Installation version PROD'
          run: make env-prod
        - name: 'Check running containers'
          run: make docker-ls
        - name: 'BDD MIGRATE'
          run: make bdd-migrate
        # - name: 'Run the fixtures'
        #   run: make bdd-fixtures
