name: Continuous Integration
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Repository lampy
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: koromerzhin/lampy
          path: lampy
      - name: Install npm dependencies
        run: npm install
      - name: 'set .env'
        run: 'cp apps/.env.test apps/.env'
      - name: 'SET BDD'
        run: npm run bddset-mariadb
      - name: 'Launch Lampy'
        run: cd lampy && npm run exec
      - name: 'Image pull'
        run: npm run docker_getpull-image
      - name: 'Build containers'
        run: npm run docker_deploy
      - name: 'Waiting'
        run: npm run docker_waiting
      - name: linter readme.md
        run: npx markdownlint readme.md
      - name: linter SCSS
        run: make linter stylelint
      - name: "install PHAR"
        run: npx korojscommands php_download-phar
      - name: 'docker ls'
        run: npm run docker_ls
      - name: linter PHP Code Sniffer
        run: make linter phpcs-onlyerror
      - name: linter PHP MD
        run: make linter phpmd
      - name: linter PHPMND
        run: make linter phpmnd
      - name: Add assets
        run: make assets
      - name: Test lancement bootstrap
        run: make encore dev
      - name: Linter twig
        run: make linter twig
      - name: Linter yaml
        run: make linter yaml
      - name: linter phpstan
        run: make linter phpstan
      - name: 'BDD MIGRATE'
        run: make bdd migrate
      - name: 'BDD Schema update'
        run: make bdd schemaupdate
      - name: 'Run the fixtures'
        run: make bdd fixtures
      - name: Run Acceptance Tests
        run: make tests behat