name: docker
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Docker swarm init'
        run: docker swarm init --default-addr-pool 10.20.0.0/16
      - name: 'Create proxy network'
        run: make docker-create-network
      - name: 'Build containers'
        run: make docker-deploy-ci
      - name: 'Make sleep'
        run: make sleep
      - name: 'Check running containers'
        run: make docker-ls
      - name: 'Installation variable environnement'
        run: make env-dev
      - name: 'Composer install'
        run: make composer-dev-ci
      - name: 'BDD MIGRATE'
        run: make bdd-migrate
      - name: 'Run the fixtures'
        run: make bdd-fixtures
      - name: Run Acceptance Tests
        run: make tests-behat
      - name: Run Tests
        run: make tests-simple-phpunit-unit-integration

