name: Continuous Integration
on: [push]
jobs:
  launch:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Repository lampy
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: 'v2.0'
        repository: koromerzhin/lampy
        path: lampy
    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install npm dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install
    - name: 'set apps/.env'
      run: 'cp apps/.env.test apps/.env'
    - name: 'set .env'
      run: 'cp .env.example .env'
    - name: 'SET BDD'
      run: npm run bdd:mariadb
    - name: 'Launch Lampy'
      run: cd lampy && npm run exec
    - name: 'Image pull'
      run: npm run docker:getpull-image
    - name: 'Build containers'
      run: npm run docker:deploy
    - name: 'Waiting'
      run: npm run docker:waiting
    - name: Add assets
      run: npm run assets
    - name: Test lancement bootstrap
      run: npm run encore:prod
    - name: 'BDD MIGRATE'
      run: npm run doctrine:migrate
    - name: 'BDD Schema update'
      run: npm run doctrine:schema:update
    - name: 'Run the fixtures'
      run: npm run doctrine:fixtures
    - name: 'Labstag install'
      run: npm run cmd:labstag:all
    - name: Cypress run
      uses: cypress-io/github-action@v5
    - name: Archive screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: cypress/
